export interface User { id:string; name:string; email:string; role:'user'|'admin'|'support'|'editor'; createdAt:string; updatedAt?:string; termsAcceptedAt?:string; privacyAcceptedAt?:string; termsVersion?:string; privacyVersion?:string; currentCompanyId?:string; avatarUrl?:string; emailVerified?:boolean; }
export interface Wallet { id:string; userId:string; balance:number; bonusBalance:number; totalUsed:number; totalReceived:number; reservedCredits:number; planId:string; planStatus?:'free'|'active'|'cancel_at_period_end'|'cancelled'|'past_due'; currentPeriodEnd?:string|null; updatedAt:string; }
export interface CreditTransaction { id:string; userId:string; companyId?:string; type:'purchase'|'subscription'|'bonus'|'usage'|'refund'|'admin_adjustment'|'reversal'|'reservation'; source:string; amount:number; balanceBefore:number; balanceAfter:number; referenceId?:string; idempotencyKey?:string; timestamp:string; metadata?:Record<string,any>; }
export interface MarketingProfile { niche:string; targetAudience:string; persona:string; toneOfVoice:string; brandIdentitySummary:string; goals:string; keyDifferentials:string; forbiddenWords:string[]; preferredCtas:string[]; topKeywords:string[]; lastUpdated:string; }
export interface Company { id:string; userId:string; name:string; slug:string; logoUrl?:string; logoStoragePath?:string; description:string; businessType?:'online'|'physical'|'hybrid'; onlineChannels?:string[]; website?:string; androidApp?:string; iosApp?:string; phone?:string; whatsapp?:string; email?:string; address?:string; city?:string; state?:string; country?:string; category:string; segment?:string; products:string[]; services:string[]; targetAudience?:string; coverageRegion?:string; differentials?:string; brandTone?:string; goals?:string; competitors?:string[]; keywords:string[]; socialLinks?:{instagram?:string;facebook?:string;tiktok?:string;youtube?:string;linkedin?:string;pinterest?:string;x?:string}; isPublicInVitrine:boolean; marketingProfile?:MarketingProfile; createdAt:string; updatedAt:string; }
export interface ContentItem { id:string; userId:string; companyId:string; type:'post'|'image'|'video_script'|'article'|'cta'|'headline'|'carousel'|'email'; title:string; headline?:string; body:string; cta?:string; hashtags:string[]; keywords:string[]; visualPrompt?:string; imageUrl?:string; videoScript?:string; carouselSlides?:{title:string;text:string;visualDesc?:string}[]; targetPlatform?:string; tone?:string; creditsUsed:number; status:'draft'|'saved'|'scheduled'|'published'; createdAt:string; updatedAt:string; metadata?:Record<string,any>; }
export interface Campaign { id:string; userId:string; companyId:string; name:string; objective:string; targetPlatforms:string[]; targetAudience?:string; budgetCredits?:number; startDate:string; endDate?:string; status:'draft'|'pending'|'scheduled'|'active'|'paused'|'completed'|'failed'; contentItemIds:string[]; metrics:{reach:number;clicks:number;leads:number;conversions:number;shares:number;comments:number}; createdAt:string; updatedAt:string; }
export interface ScheduledPost { id:string; userId:string; companyId:string; contentItemId:string; platforms:string[]; scheduledFor:string; status:'scheduled'|'publishing'|'published'|'failed'|'cancelled'; publishedAt?:string; errorMessage?:string; autopilotGenerated?:boolean; retryCount?:number; publicationResults?:Array<{platform:string;success:boolean;externalId?:string;error?:string}>; createdAt:string; updatedAt?:string; }
export interface SocialConnection { id:string; userId:string; companyId:string; provider:'instagram'|'facebook'|'tiktok'|'youtube'|'linkedin'|'pinterest'|'x'; accountName:string; accountId:string; scopes:string[]; expiresAt?:string; connectedAt:string; status:'connected'|'expired'|'error'; }
export interface SeoReport { id:string; userId:string; companyId:string; url:string; title?:string; metaDescription?:string; h1s:string[]; h2s:string[]; keywords:{word:string;count:number;density:string}[]; seoScore:number; criteriaBreakdown:{hasTitle:boolean;titleLengthValid:boolean;hasDescription:boolean;descriptionLengthValid:boolean;hasH1:boolean;singleH1:boolean;hasKeywordsInHeadings:boolean;contentLengthSufficient:boolean;hasHttps:boolean;hasCanonical:boolean}; recommendations:string[]; generatedOutline?:string[]; faqSuggestions?:{question:string;answer:string}[]; createdAt:string; }
export interface BlogPost { id:string; title:string; slug:string; summary:string; content:string; featuredImageUrl?:string; author:string; category:string; tags:string[]; companyId?:string; isFrocMagazineSponsored?:boolean; seoTitle?:string; seoDescription?:string; status:'published'|'draft'|'archived'; publishedAt?:string; createdAt:string; updatedAt?:string; }
export interface AutopilotConfig { id:string; userId:string; companyId:string; enabled:boolean; mode:'manual_approval'|'automatic'; frequency:'daily'|'3_times_week'|'weekly'; preferredDays:number[]; preferredHours:number[]; targetPlatforms:string[]; primaryGoal:string; maxMonthlyCredits:number; usedCreditsThisMonth:number; lastRunAt?:string; nextRunAt?:string; usageMonth?:string; }
export interface Plan { id:string; name:string; price:number; period:string; credits:number; bonusCredits:number; totalCredits:number; popular:boolean; features:string[]; }

export { CREDIT_COSTS } from './lib/creditCosts';
export type { CreditOperation } from './lib/creditCosts';

